
clc
clear
close all

%%This MATLAB program is to read and write CSV files and filter the PPG signal
mycsv = fopen('stream_raw_matlab.csv', 'r');
fgetl(mycsv); % skip the first row
mcu_adc_raw = fscanf(mycsv, '%d,%f', [2 Inf]);
mcu_adc_raw = mcu_adc_raw';
t = mcu_adc_raw(:,1);
mcu_adc_raw = mcu_adc_raw(:,2);

% plot the signal into frequency domain
X_mags = abs(fft(mcu_adc_raw));

%plot first half of DFT
num_bins = length(X_mags);
plot([0:1/(num_bins/2 - 1):1], X_mags(1:num_bins/2))
xlabel('Freuqency')
ylabel('magnitude')
figure()

N=length(mcu_adc_raw);
demod_lpf_ord=2;

%% Method 1: apply lowpass filter
[b,a] = butter(demod_lpf_ord,0.24,'low');
y = filtfilt(b,a,mcu_adc_raw);

% Plotting
plot(mcu_adc_raw,'r-')

%% Method 2: apply lowpass filter
% Decompose Signal using the MODWT
% Generated by MATLAB(R) 9.10 and Wavelet Toolbox 5.6.
% Logical array for selecting reconstruction elements
levelForReconstruction = [true, true, true, true, true, false, false, false, false, false, false, false, false, false, true];
% Perform the decomposition using modwt
wt = modwt(y, 'sym4', 14);
% Construct MRA matrix using modwtmra
mra = modwtmra(wt, 'sym4');
% Sum along selected multiresolution signals
mcu_adc_raw1 = sum(mra(levelForReconstruction,:),1);

outputcsv = fopen('reconstructed_stream_raw.csv', 'w');
mcu_adc_raw1 = mcu_adc_raw1';
fprintf(outputcsv,'%f\n',mcu_adc_raw1(:,:));

hold all;grid on;
plot(mcu_adc_raw1, 'b');
ylabel('magnitude');
legend('original ppg','filtered ppg','Location','southeast');
xlabel('time');